package com.common.util.sound;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JButton;

import com.common.util.sound.SoundPlayer;

/**
 * Clase que permite desplegar una ventana para probar las alarmas que hay dentro del sistema.
 * 
 * @version 1.0
 */
@SuppressWarnings("serial")
public class PlayerTest extends javax.swing.JFrame {

	/**
	 * El objeto reproductor del sistema.
	 */
	private SoundPlayer reproductor;

	/**
	 * El constructor de un reproductor de las alarmas.
	 */
	public PlayerTest() {
		super();
		this.getContentPane().setBounds(new Rectangle(0, 0, 400, 100));
		this.initComponents();
		this.loadAlarmsInComboBox();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		this.setTitle("Alarmas");
		this.setLocationRelativeTo(null);
		this.getContentPane().setLayout(null);
		this.setResizable(false);
		this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		this.setPreferredSize(new Dimension(510, 125));

		this.comboAlarmas = new javax.swing.JComboBox<File>();
		this.comboAlarmas.setBounds(10, 11, 485, 30);

		this.comboAlarmas.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PlayerTest.this.comboAlarmasActionPerformed(evt);
			}
		});
		this.getContentPane().add(this.comboAlarmas);

		javax.swing.JButton botonPlay = new javax.swing.JButton();
		botonPlay.setBounds(10, 52, 89, 36);
		botonPlay.setText("Play");
		botonPlay.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PlayerTest.this.reproductor.play();
			}
		});
		this.getContentPane().add(botonPlay);

		javax.swing.JButton botonLoop = new javax.swing.JButton();
		botonLoop.setBounds(109, 52, 89, 36);
		botonLoop.setText("Loop");
		botonLoop.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PlayerTest.this.reproductor.loop();
			}
		});
		this.getContentPane().add(botonLoop);

		javax.swing.JButton botonStop = new javax.swing.JButton();
		botonStop.setBounds(307, 52, 89, 36);
		botonStop.setText("Stop");
		botonStop.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PlayerTest.this.reproductor.stop();
			}
		});

		JButton botonPausa = new JButton("Pausar");
		botonPausa.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				PlayerTest.this.reproductor.pause();
			}
		});
		botonPausa.setBounds(208, 52, 89, 36);
		this.getContentPane().add(botonPausa);
		this.getContentPane().add(botonStop);

		JButton botonReiniciar = new JButton("Reini");
		botonReiniciar.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				PlayerTest.this.reproductor.reboot();
			}
		});
		botonReiniciar.setBounds(406, 52, 89, 36);
		this.getContentPane().add(botonReiniciar);

		this.pack();
	}

	private void comboAlarmasActionPerformed(java.awt.event.ActionEvent evt) {
		if (this.reproductor != null) {
			this.reproductor.stop();
		}
		if (this.comboAlarmas.getSelectedIndex() != -1) {
			this.reproductor = new SoundPlayer((File) this.comboAlarmas.getSelectedItem());
		}
	}

	private javax.swing.JComboBox<File> comboAlarmas;

	/**
	 * Función encargada de cargar dentro del combo todas las alrmas que hay dentro del sistema para probarse.
	 */
	private void loadAlarmsInComboBox() {
		this.comboAlarmas.addItem(new File(PlayerTest.class.getResource("/com/commons/util/sound/Alarm.wav").getFile()));
		this.comboAlarmas.setSelectedIndex(0);
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				PlayerTest dialog = new PlayerTest();
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
}
